- id: '1565816727955'
  alias: Ping_telegram
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
        command: '/ping'
  condition: []
  action:
  - alias: ''
    data: {message: 'pong'}
    service: telegram_bot.send_message
