# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

frontend:
    themes: !include themes.yaml

# Text to speech
tts:
  - platform: google_translate

# include other files
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include sensor.yaml
switch: !include switches.yaml
binary_sensor: !include binary_sensor.yaml
#input_select: !include input_select.yaml
#input_boolean: !include input_boolean.yaml
#input_number: !include input_number.yaml
#input_text: !include input_text.yaml

# log level
logger:
  default: error

# recorder config
recorder:
  purge_keep_days: 1
  purge_interval: 1
  include:
    domains:
      - sensor

# Telegram Bot
telegram_bot:
  - platform: polling
    api_key: !secret telegram_api
    allowed_chat_ids:
      - !secret telegram_chat_id

# Notify section
notify:
  - name: PING_PONG
    platform: telegram
    chat_id: !secret telegram_chat_id
      

  